# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Clever Minds Development Center
collections:
  courses:
    title: Courses
    output: false
  fees:
    title: fees
    output: false
  calendar_months:
    title: calendar_months
    output: false
  posts:
    title: Posts
    output: true
email: cmdc.ph@gmail.com
description: We nurture and support your child's growth and development.
baseurl: ""
url: "http://cleverminds.ph"
twitter_username: cmdcph
github_username:  cmdcph
permalink: none

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
