---
title: Clever Minds Development Center
timezone: Asia/Singapore
collections:
  courses:
    title: Courses
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  activities:
    title: activities
    output: false
  calendar_months:
    title: calendar_months
    output: false
  fees:
    title: fees
    output: false
  teachers:
    title: teachers
    output: false
description: We nurture and support your child's growth and development.
services: Summer Classes & Tutorial Services
email: cmdc.ph@gmail.com
phone: "+63-908-525-9178"
address_line_1: 352 Sitio Lote, Brgy. Lecheria
address_line_2: Calamba City, Laguna
address_line_3: Philippines 4027
business_hours: Monday - Friday, 8 AM to 6 PM
baseurl: 
domain: cleverminds.ph
url: https://cleverminds.ph
credits: erikathea
credits_url: https://erikathea.com
facebook: https://www.facebook.com/cmdcph
social_media: cmdcph
twitter_username: cmdcph
github_username: cmdcph
permalink: none
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
