# Site settings
title: Clever Minds Development Center
email: cmdc.ph@gmail.com
description: Clever Minds Development Center - As the children begin to develop trust and confidence their development are influenced by the experiences they get from their environment hence they should be given consistent nurturance, sensory stimulation, and a good role model.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmdcph.com" # the base hostname & protocol for your site
twitter_username: cmdcph
facebook_username:  cmdcph

# Build settings
markdown: kramdown
