---
title: Clever Minds Development Center
timezone: UTC
collections:
  courses:
    title: Courses
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  calendar_months:
    title: calendar_months
    output: false
  fees:
    title: fees
    output: false
  teachers:
    title: teachers
    output: false
email: cmdc.ph@gmail.com
description: We nurture and support your child's growth and development.
baseurl: ''
url: http://cleverminds.ph
twitter_username: cmdcph
github_username: cmdcph
permalink: none
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
